default:
  image: python:3

before_script:
  - pip install --upgrade setuptools wheel
  - sed -i "s/__version__ = 'dev'/__version__ = '0.11-2'/" efidgy/__init__.py
  - python setup.py develop

test:
  stage: test
  only:
    - ci
  script:
    - python -m unittest

publish:
  stage: publish
  only:
    - ci
  script:
    - python setup.py sdist bdist_wheel
    - echo python -m twine upload dist/*
