default:
  image: python:3

before_script:
  - pip install --upgrade setuptools wheel

build:
  stage: build
  only:
    - ci
  script:
    - python setup.py develop

test:
  stage: test
  only:
    - ci
  script:
    - python -m unittest

upload:
  stage: deploy
  only:
    - ci
  script:
    - python setup.py sdist bdist_wheel
    - echo python -m twine upload dist/*
